=== sacredbanana/AmigaSDK-gcc/ppc-amigaos/SDK/include/interfaces/library.dtd
<?xml version="1.0" encoding="iso-8859-1"?>
<!ELEMENT library (include*, interface+)>
<!ATTLIST library
    basename    CDATA   #REQUIRED
    openname    CDATA   "none"
>

<!ELEMENT interface (description?, method+)>
<!ATTLIST interface
    name        CDATA   #REQUIRED
    version     CDATA   "1.0"
    flags       (protected|private|none) "none"
    struct	CDATA	#REQUIRED
    prefix	CDATA	"_impl_"
    asmprefix   CDATA   "none"
>

<!ELEMENT method (arg*,description?,vararg?)>
<!ATTLIST method
    name        CDATA   #REQUIRED
    result      CDATA   "void"
    status      CDATA   "implemented"
>

<!ELEMENT arg EMPTY>
<!ATTLIST arg
    name        CDATA   #REQUIRED
    type        CDATA   #REQUIRED
>

<!ELEMENT description (#PCDATA)>

<!ELEMENT include (#PCDATA)>

<!ELEMENT vararg EMPTY>
<!ATTLIST vararg
    name	CDATA   #REQUIRED
    type	CDATA	#REQUIRED
>

=== sacredbanana/AmigaSDK-gcc/ppc-amigaos/SDK/include/interfaces/bzip2.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE library SYSTEM "library.dtd">
<!-- autogenerated by fdtrans v52.1 -->
<library name="bzip2" basename="BZip2Base" basetype="Library" openname="bzip2.library">
	<include>libraries/bzip2.h</include>
	<include>stdio.h</include>
	<interface name="main" version="1.0" struct="BZip2IFace" prefix="_BZip2_" asmprefix="IBZip2" global="IBZip2">
		<method name="Obtain" result="uint32"/>
		<method name="Release" result="uint32"/>
		<method name="Expunge" result="void" status="unimplemented"/>
		<method name="Clone" result="struct Interface *" status="unimplemented"/>
		<method name="BZ2_bzlibVersion" result="const char *">
		</method>
		<method name="BZ2_bzCompressInit" result="int">
			<arg name="strm" type="bz_stream *"/>
			<arg name="blockSize100k" type="int"/>
			<arg name="verbosity" type="int"/>
			<arg name="workFactor" type="int"/>
		</method>
		<method name="BZ2_bzCompress" result="int">
			<arg name="strm" type="bz_stream *"/>
			<arg name="action" type="int"/>
		</method>
		<method name="BZ2_bzCompressEnd" result="int">
			<arg name="strm" type="bz_stream *"/>
		</method>
		<method name="BZ2_bzDecompressInit" result="int">
			<arg name="strm" type="bz_stream *"/>
			<arg name="verbosity" type="int"/>
			<arg name="small" type="int"/>
		</method>
		<method name="BZ2_bzDecompress" result="int">
			<arg name="strm" type="bz_stream *"/>
		</method>
		<method name="BZ2_bzDecompressEnd" result="int">
			<arg name="strm" type="bz_stream *"/>
		</method>
		<method name="BZ2_bzBuffToBuffCompress" result="int">
			<arg name="dest" type="char *"/>
			<arg name="destLen" type="unsigned int *"/>
			<arg name="source" type="char *"/>
			<arg name="sourceLen" type="unsigned int"/>
			<arg name="blockSize100k" type="int"/>
			<arg name="verbosity" type="int"/>
			<arg name="workFactor" type="int"/>
		</method>
		<method name="BZ2_bzBuffToBuffDecompress" result="int">
			<arg name="dest" type="char *"/>
			<arg name="destLen" type="unsigned int *"/>
			<arg name="source" type="char *"/>
			<arg name="sourceLen" type="unsigned int"/>
			<arg name="small" type="int"/>
			<arg name="verbosity" type="int"/>
		</method>
		<method name="BZ2_bzReadOpen" result="BZFILE *">
			<arg name="bzerror" type="int *"/>
			<arg name="f" type="FILE *"/>
			<arg name="verbosity" type="int"/>
			<arg name="small" type="int"/>
			<arg name="unused" type="void *"/>
			<arg name="nUnused" type="int"/>
		</method>
		<method name="BZ2_bzReadClose" result="void">
			<arg name="bzerror" type="int *"/>
			<arg name="b" type="BZFILE *"/>
		</method>
		<method name="BZ2_bzReadGetUnused" result="void">
			<arg name="bzerror" type="int *"/>
			<arg name="b" type="BZFILE *"/>
			<arg name="unused" type="void **"/>
			<arg name="nUnused" type="int *"/>
		</method>
		<method name="BZ2_bzRead" result="int">
			<arg name="bzerror" type="int *"/>
			<arg name="b" type="BZFILE *"/>
			<arg name="buf" type="void *"/>
			<arg name="len" type="int"/>
		</method>
		<method name="BZ2_bzWriteOpen" result="BZFILE *">
			<arg name="bzerror" type="int *"/>
			<arg name="f" type="FILE *"/>
			<arg name="blockSize100k" type="int"/>
			<arg name="verbosity" type="int"/>
			<arg name="workFactor" type="int"/>
		</method>
		<method name="BZ2_bzWrite" result="void">
			<arg name="bzerror" type="int *"/>
			<arg name="b" type="BZFILE *"/>
			<arg name="buf" type="void *"/>
			<arg name="len" type="int"/>
		</method>
		<method name="BZ2_bzWriteClose" result="void">
			<arg name="bzerror" type="int *"/>
			<arg name="b" type="BZFILE *"/>
			<arg name="abandon" type="int"/>
			<arg name="nbytes_in" type="unsigned int *"/>
			<arg name="nbytes_out" type="unsigned int *"/>
		</method>
		<method name="BZ2_bzWriteClose64" result="void">
			<arg name="bzerror" type="int *"/>
			<arg name="b" type="BZFILE *"/>
			<arg name="abandon" type="int"/>
			<arg name="nbytes_in_lo32" type="unsigned int *"/>
			<arg name="nbytes_in_hi32" type="unsigned int *"/>
			<arg name="nbytes_out_lo32" type="unsigned int *"/>
			<arg name="nbytes_out_hi32" type="unsigned int *"/>
		</method>
		<method name="BZ2_bzopen" result="BZFILE *">
			<arg name="path" type="const char *"/>
			<arg name="mode" type="const char *"/>
		</method>
		<method name="BZ2_bzdopen" result="BZFILE *">
			<arg name="fd" type="int"/>
			<arg name="mode" type="const char *"/>
		</method>
		<method name="BZ2_bzread" result="int">
			<arg name="b" type="BZFILE *"/>
			<arg name="buf" type="void *"/>
			<arg name="len" type="int"/>
		</method>
		<method name="BZ2_bzwrite" result="int">
			<arg name="b" type="BZFILE *"/>
			<arg name="buf" type="void *"/>
			<arg name="len" type="int"/>
		</method>
		<method name="BZ2_bzflush" result="int">
			<arg name="b" type="BZFILE *"/>
		</method>
		<method name="BZ2_bzclose" result="void">
			<arg name="b" type="BZFILE *"/>
		</method>
		<method name="BZ2_bzerror" result="const char *">
			<arg name="b" type="BZFILE *"/>
			<arg name="errnum" type="int *"/>
		</method>
	</interface>
</library>

=== sacredbanana/AmigaSDK-gcc/ppc-amigaos/SDK/include/interfaces/cardres.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE library SYSTEM "library.dtd">
<!-- autogenerated by fdtrans v50.9 -->
<library name="cardres" basename="CardResource" openname="include/cardres.library">
	<include>exec/types.h</include>
	<include>exec/resident.h</include>
	<include>resources/card.h</include>
	<interface name="main" version="1.0" struct="CardIFace" prefix="_Card_" asmprefix="ICard" global="ICard">
		<method name="Obtain" result="ULONG"/>
		<method name="Release" result="ULONG"/>
		<method name="Expunge" result="void" status="unimplemented"/>
		<method name="Clone" result="struct Interface *" status="unimplemented"/>
		<method name="OwnCard" result="struct CardHandle *">
			<arg name="handle" type="struct CardHandle *"/>
		</method>
		<method name="ReleaseCard" result="VOID">
			<arg name="handle" type="struct CardHandle *"/>
			<arg name="flags" type="ULONG"/>
		</method>
		<method name="GetCardMap" result="struct CardMemoryMap *">
		</method>
		<method name="BeginCardAccess" result="BOOL">
			<arg name="handle" type="struct CardHandle *"/>
		</method>
		<method name="EndCardAccess" result="BOOL">
			<arg name="handle" type="struct CardHandle *"/>
		</method>
		<method name="ReadCardStatus" result="UBYTE">
		</method>
		<method name="CardResetRemove" result="BOOL">
			<arg name="handle" type="struct CardHandle *"/>
			<arg name="flag" type="ULONG"/>
		</method>
		<method name="CardMiscControl" result="UBYTE">
			<arg name="handle" type="struct CardHandle *"/>
			<arg name="control_bits" type="UBYTE"/>
		</method>
		<method name="CardAccessSpeed" result="ULONG">
			<arg name="handle" type="struct CardHandle *"/>
			<arg name="nanoseconds" type="ULONG"/>
		</method>
		<method name="CardProgramVoltage" result="LONG">
			<arg name="handle" type="struct CardHandle *"/>
			<arg name="voltage" type="ULONG"/>
		</method>
		<method name="CardResetCard" result="BOOL">
			<arg name="handle" type="struct CardHandle *"/>
		</method>
		<method name="CopyTuple" result="BOOL">
			<arg name="handle" type="const struct CardHandle *"/>
			<arg name="buffer" type="UBYTE *"/>
			<arg name="tuplecode" type="ULONG"/>
			<arg name="size" type="ULONG"/>
		</method>
		<method name="DeviceTuple" result="ULONG">
			<arg name="tuple_data" type="const UBYTE *"/>
			<arg name="storage" type="struct DeviceTData *"/>
		</method>
		<method name="IfAmigaXIP" result="struct Resident *">
			<arg name="handle" type="const struct CardHandle *"/>
		</method>
		<method name="CardForceChange" result="BOOL">
		</method>
		<method name="CardChangeCount" result="ULONG">
		</method>
		<method name="CardInterface" result="ULONG">
		</method>
	</interface>
</library>

=== sacredbanana/AmigaSDK-gcc/amigaos4/sdk/ppc-amigaos/SDK/include/interfaces/bootsd.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE library SYSTEM "library.dtd">
<library name="bootsd" basename="BootSDBase" openname="bootsd.resource">
<interface name="main" version="1.0" flags="protected" struct="BootSDIFace" prefix="_bootsd_" global="IBootSD">

<method name="Obtain" result="uint32"></method>
<method name="Release" result="uint32"></method>
<method name="Expunge" result="void" status="unimplemented"></method>
<method name="Clone" result="struct Interface *" status="unimplemented"></method>

<method name="AllocResource" result="APTR">
	<arg name="error" type="int32 *"/>
</method>

<method name="FreeResource" result="BOOL">
	<arg name="unit" type="APTR"/>
</method>

<method name="GetGeometry" result="APTR">
	<arg name="unit" type="APTR"/>
	<arg name="error" type="int32 *"/>
	<arg name="geom" type ="struct DosEnvec *"/>
</method>

<method name="ReadSDCard" result="uint32">
	<arg name="unit" type="APTR"/>
	<arg name="error" type="int32 *"/>
	<arg name="buffer" type="APTR"/>
	<arg name="startBlock" type ="uint32"/>
	<arg name="numBlocks" type ="uint32"/>
</method>

<method name="WriteSDCard" result="uint32">
	<arg name="unit" type="APTR"/>
	<arg name="error" type="int32 *"/>
	<arg name="buffer" type="APTR"/>
	<arg name="startBlock" type ="uint32"/>
	<arg name="numBlocks" type ="uint32"/>
</method>

</interface>
</library>

=== sacredbanana/AmigaSDK-gcc/amigaos4/sdk/ppc-amigaos/SDK/include/interfaces/layout.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE library SYSTEM "library.dtd">
<library name="layout" basename="LayoutBase" classname="LayoutClass" openname="gadgets/layout.gadget">
	<include>intuition/intuition.h</include>
	<include>intuition/classes.h</include>
	<include>gadgets/layout.h</include>
	<interface name="main" version="1.0" struct="LayoutIFace" prefix="_Layout_" asmprefix="ILayout" global="ILayout">
		<method name="Obtain" result="ULONG"/>
		<method name="Release" result="ULONG"/>
		<method name="Expunge" result="void" status="unimplemented"/>
		<method name="Clone" result="struct Interface *" status="unimplemented"/>
		<method name="LAYOUT_GetClass" result="Class *">
		</method>
		<method name="ActivateLayoutGadget" result="BOOL">
			<arg name="gadget" type="struct Gadget *"/>
			<arg name="window" type="struct Window *"/>
			<arg name="requester" type="struct Requester *"/>
			<arg name="object" type="ULONG"/>
		</method>
		<method name="FlushLayoutDomainCache" result="VOID">
			<arg name="gadget" type="struct Gadget *"/>
		</method>
		<method name="RethinkLayout" result="BOOL">
			<arg name="gadget" type="struct Gadget *"/>
			<arg name="window" type="struct Window *"/>
			<arg name="requester" type="struct Requester *"/>
			<arg name="refresh" type="BOOL"/>
		</method>
		<method name="LayoutLimits" result="VOID">
			<arg name="gadget" type="struct Gadget *"/>
			<arg name="limits" type="struct LayoutLimits *"/>
			<arg name="font" type="struct TextFont *"/>
			<arg name="screen" type="struct Screen *"/>
		</method>
		<method name="PAGE_GetClass" result="Class *">
		</method>
		<method name="SetPageGadgetAttrsA" result="ULONG">
			<arg name="gadget" type="struct Gadget *"/>
			<arg name="object" type="Object *"/>
			<arg name="window" type="struct Window *"/>
			<arg name="requester" type="struct Requester *"/>
			<arg name="tags" type="struct TagItem *"/>
		</method>
		<method name="SetPageGadgetAttrs" result="ULONG">
			<arg name="gadget" type="struct Gadget *"/>
			<arg name="object" type="Object *"/>
			<arg name="window" type="struct Window *"/>
			<arg name="requester" type="struct Requester *"/>
			<vararg name="tag1" type="Tag"/>
		</method>
		<method name="RefreshPageGadget" result="VOID">
			<arg name="gadget" type="struct Gadget *"/>
			<arg name="object" type="Object *"/>
			<arg name="window" type="struct Window *"/>
			<arg name="requester" type="struct Requester *"/>
		</method>
	</interface>
</library>

=== sacredbanana/AmigaSDK-gcc/amigaos4/sdk/ppc-amigaos/SDK/include/interfaces/textclip.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE library SYSTEM "library.dtd">
<!-- autogenerated by fdtrans v51.19 -->
<library name="textclip" basename="TextClipBase" openname="textclip.library">
	<include>exec/types.h</include>
	<interface name="main" version="1.0" struct="TextClipIFace" prefix="_TextClip_" asmprefix="ITextClip" global="ITextClip">
		<method name="Obtain" result="ULONG"/>
		<method name="Release" result="ULONG"/>
		<method name="Expunge" result="void" status="unimplemented"/>
		<method name="Clone" result="struct Interface *" status="unimplemented"/>
		<method name="WriteClipVector" result="LONG">
			<arg name="vector" type="CONST_STRPTR"/>
			<arg name="size" type="ULONG"/>
		</method>
		<method name="ReadClipVector" result="LONG">
			<arg name="bufptr" type="STRPTR *"/>
			<arg name="sizptr" type="ULONG *"/>
		</method>
		<method name="DisposeClipVector" result="VOID">
			<arg name="vector" type="STRPTR"/>
		</method>
	</interface>
</library>

=== sacredbanana/AmigaSDK-gcc/amigaos4/sdk/ppc-amigaos/SDK/include/interfaces/lowlevel.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE library SYSTEM "library.dtd">
<!-- autogenerated by fdtrans v50.8 -->
<library name="lowlevel" basename="LowLevelBase" openname="lowlevel.library">
	<include>exec/types.h</include>
	<include>exec/interrupts.h</include>
	<include>utility/tagitem.h</include>
	<include>devices/timer.h</include>
	<include>libraries/lowlevel.h</include>
	<interface name="main" version="1.0" struct="LowLevelIFace" prefix="_LowLevel_" asmprefix="ILowLevel" global="ILowLevel">
		<method name="Obtain" result="ULONG"/>
		<method name="Release" result="ULONG"/>
		<method name="Expunge" result="void" status="unimplemented"/>
		<method name="Clone" result="struct Interface *" status="unimplemented"/>
		<method name="ReadJoyPort" result="ULONG">
			<arg name="port" type="ULONG"/>
		</method>
		<method name="GetLanguageSelection" result="UBYTE">
		</method>
		<method name="SetLanguageSelection" result="VOID" status="private">
			<arg name="language" type="ULONG"/>
		</method>
		<method name="GetKey" result="ULONG">
		</method>
		<method name="QueryKeys" result="VOID">
			<arg name="queryArray" type="struct KeyQuery *"/>
			<arg name="arraySize" type="UBYTE"/>
		</method>
		<method name="AddKBInt" result="APTR">
			<arg name="intRoutine" type="const APTR"/>
			<arg name="intData" type="const APTR"/>
		</method>
		<method name="RemKBInt" result="VOID">
			<arg name="intHandle" type="APTR"/>
		</method>
		<method name="SystemControlA" result="ULONG">
			<arg name="tagList" type="const struct TagItem *"/>
		</method>
		<method name="SystemControl" result="ULONG">
			<vararg name="firstTag" type="Tag"/>
		</method>
		<method name="AddTimerInt" result="APTR">
			<arg name="intRoutine" type="const APTR"/>
			<arg name="intData" type="const APTR"/>
		</method>
		<method name="RemTimerInt" result="VOID">
			<arg name="intHandle" type="APTR"/>
		</method>
		<method name="StopTimerInt" result="VOID">
			<arg name="intHandle" type="APTR"/>
		</method>
		<method name="StartTimerInt" result="VOID">
			<arg name="intHandle" type="APTR"/>
			<arg name="timeInterval" type="ULONG"/>
			<arg name="continuous" type="BOOL"/>
		</method>
		<method name="ElapsedTime" result="ULONG">
			<arg name="context" type="struct EClockVal *"/>
		</method>
		<method name="AddVBlankInt" result="APTR">
			<arg name="intRoutine" type="const APTR"/>
			<arg name="intData" type="const APTR"/>
		</method>
		<method name="RemVBlankInt" result="VOID">
			<arg name="intHandle" type="APTR"/>
		</method>
		<method name="KillReq" result="VOID" status="private">
		</method>
		<method name="RestoreReq" result="VOID" status="private">
		</method>
		<method name="SetJoyPortAttrsA" result="BOOL">
			<arg name="portNumber" type="ULONG"/>
			<arg name="tagList" type="const struct TagItem *"/>
		</method>
		<method name="SetJoyPortAttrs" result="BOOL">
			<arg name="portNumber" type="ULONG"/>
			<vararg name="firstTag" type="Tag"/>
		</method>
	</interface>
</library>

=== sacredbanana/AmigaSDK-gcc/amigaos4/sdk/ppc-amigaos/SDK/include/interfaces/btree.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE library SYSTEM "library.dtd">
<!-- autogenerated by fdtrans v52.1 -->
<library name="btree" basename="BTreeBase" basetype="Library" openname="btree.library">
	<include>exec/types.h</include>
	<include>libraries/btree.h</include>
	<interface name="main" version="1.0" struct="BTreeIFace" prefix="_BTree_" asmprefix="IBTree" global="IBTree">
		<method name="Obtain" result="uint32"/>
		<method name="Release" result="uint32"/>
		<method name="Expunge" result="void" status="unimplemented"/>
		<method name="Clone" result="struct Interface *" status="unimplemented"/>
		<method name="CreateTree" result="APTR">
			<arg name="Type" type="ULONG"/>
			<arg name="argArray" type="const struct BTArgArray *"/>
		</method>
		<method name="DeleteTree" result="void">
			<arg name="Tree" type="APTR"/>
		</method>
		<method name="InsertTreeNode" result="APTR">
			<arg name="Tree" type="APTR"/>
			<arg name="Key" type="CONST_APTR"/>
			<arg name="Data" type="CONST_APTR"/>
		</method>
		<method name="DeleteTreeNode" result="void">
			<arg name="Tree" type="APTR"/>
			<arg name="Node" type="APTR"/>
		</method>
		<method name="GetTreeNodeKey" result="APTR">
			<arg name="Tree" type="CONST_APTR"/>
			<arg name="Node" type="CONST_APTR"/>
		</method>
		<method name="GetTreeNodeData" result="APTR">
			<arg name="Tree" type="CONST_APTR"/>
			<arg name="Node" type="CONST_APTR"/>
		</method>
		<method name="SuccTreeNode" result="APTR">
			<arg name="Tree" type="CONST_APTR"/>
			<arg name="Node" type="CONST_APTR"/>
		</method>
		<method name="PredTreeNode" result="APTR">
			<arg name="Tree" type="CONST_APTR"/>
			<arg name="Node" type="CONST_APTR"/>
		</method>
		<method name="MinTreeNode" result="APTR">
			<arg name="Tree" type="CONST_APTR"/>
		</method>
		<method name="MaxTreeNode" result="APTR">
			<arg name="Tree" type="CONST_APTR"/>
		</method>
		<method name="FindTreeNodeByKey" result="APTR">
			<arg name="Tree" type="CONST_APTR"/>
			<arg name="Key" type="CONST_APTR"/>
		</method>
		<method name="FindTreeNodeByData" result="APTR">
			<arg name="Tree" type="CONST_APTR"/>
			<arg name="Data" type="CONST_APTR"/>
		</method>
		<method name="ForTreeNodes" result="ULONG">
			<arg name="Tree" type="CONST_APTR"/>
			<arg name="nodeFunc" type="void (*)(APTR userData, CONST_APTR Node)"/>
			<arg name="userData" type="CONST_APTR"/>
		</method>
		<method name="EnumTreeNodes" result="ULONG">
			<arg name="Tree" type="CONST_APTR"/>
			<arg name="lowKey" type="CONST_APTR"/>
			<arg name="highKey" type="CONST_APTR"/>
			<arg name="nodeFunc" type="LONG (*)(APTR userData, CONST_APTR Node)"/>
			<arg name="userData" type="CONST_APTR"/>
		</method>
		<method name="GetTreeSize" result="ULONG">
			<arg name="Tree" type="CONST_APTR"/>
		</method>
		<method name="GetTreeHeight" result="ULONG">
			<arg name="Tree" type="CONST_APTR"/>
		</method>
		<method name="FlushTree" result="void">
			<arg name="Tree" type="APTR"/>
		</method>
		<method name="SetTreeNodeData" result="APTR">
			<arg name="Tree" type="CONST_APTR"/>
			<arg name="Node" type="APTR"/>
			<arg name="NewData" type="CONST_APTR"/>
		</method>
	</interface>
</library>

=== sacredbanana/AmigaSDK-gcc/amigaos4/sdk/ppc-amigaos/SDK/include/interfaces/cybergraphics.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE library SYSTEM "library.dtd">
<library name="cybergraphics" basename="CyberGfxBase" openname="cybergraphics.library">
	<include>exec/lists.h</include>
	<include>graphics/rastport.h</include>
	<include>graphics/view.h</include>
	<include>utility/tagitem.h</include>
	<include>utility/hooks.h</include>
	<interface name="main" version="1.0" struct="CyberGfxIFace" prefix="_CyberGfx_" asmprefix="ICyberGfx" global="ICyberGfx">
		<method name="Obtain" result="ULONG"/>
		<method name="Release" result="ULONG"/>
		<method name="Expunge" result="void" status="unimplemented"/>
		<method name="Clone" result="struct Interface *" status="unimplemented"/>
		<method name="Reserved1" result="void" status="unimplemented"/>
		<method name="Reserved2" result="void" status="unimplemented"/>
		<method name="Reserved3" result="void" status="unimplemented"/>
		<method name="Reserved4" result="void" status="unimplemented"/>
		<method name="IsCyberModeID" result="BOOL">
			<arg name="displayID" type="ULONG"/>
		</method>
		<method name="BestCModeIDTagList" result="ULONG">
			<arg name="BestModeIDTags" type="struct TagItem *"/>
		</method>
		<method name="BestCModeIDTags" result="ULONG">
			<vararg name="tag1" type="Tag"/>
		</method>
		<method name="CModeRequestTagList" result="ULONG">
			<arg name="ModeRequest" type="APTR"/>
			<arg name="ModeRequestTags" type="struct TagItem *"/>
		</method>
		<method name="CModeRequestTags" result="ULONG">
			<arg name="ModeRequest" type="APTR"/>
			<vararg name="tag1" type="Tag"/>
		</method>
		<method name="AllocCModeListTagList" result="struct List *">
			<arg name="ModeListTags" type="struct TagItem *"/>
		</method>
		<method name="AllocCModeListTags" result="struct List *">
			<vararg name="tag1" type="Tag"/>
		</method>
		<method name="FreeCModeList" result="VOID">
			<arg name="ModeList" type="struct List *"/>
		</method>
		<method name="Reserved5" result="void" status="unimplemented"/>
		<method name="ScalePixelArray" result="LONG">
			<arg name="srcRect" type="APTR"/>
			<arg name="SrcW" type="UWORD"/>
			<arg name="SrcH" type="UWORD"/>
			<arg name="SrcMod" type="UWORD"/>
			<arg name="RastPort" type="struct RastPort *"/>
			<arg name="DestX" type="UWORD"/>
			<arg name="DestY" type="UWORD"/>
			<arg name="DestW" type="UWORD"/>
			<arg name="DestH" type="UWORD"/>
			<arg name="SrcFormat" type="UBYTE"/>
		</method>
		<method name="GetCyberMapAttr" result="ULONG">
			<arg name="CyberGfxBitmap" type="struct BitMap *"/>
			<arg name="CyberAttrTag" type="ULONG"/>
		</method>
		<method name="GetCyberIDAttr" result="ULONG">
			<arg name="CyberIDAttr" type="ULONG"/>
			<arg name="CyberDisplayModeID" type="ULONG"/>
		</method>
		<method name="ReadRGBPixel" result="ULONG">
			<arg name="RastPort" type="struct RastPort *"/>
			<arg name="x" type="UWORD"/>
			<arg name="y" type="UWORD"/>
		</method>
		<method name="WriteRGBPixel" result="LONG">
			<arg name="RastPort" type="struct RastPort *"/>
			<arg name="x" type="UWORD"/>
			<arg name="y" type="UWORD"/>
			<arg name="argb" type="ULONG"/>
		</method>
		<method name="ReadPixelArray" result="ULONG">
			<arg name="destRect" type="APTR"/>
			<arg name="destX" type="UWORD"/>
			<arg name="destY" type="UWORD"/>
			<arg name="destMod" type="UWORD"/>
			<arg name="RastPort" type="struct RastPort *"/>
			<arg name="SrcX" type="UWORD"/>
			<arg name="SrcY" type="UWORD"/>
			<arg name="SizeX" type="UWORD"/>
			<arg name="SizeY" type="UWORD"/>
			<arg name="DestFormat" type="UBYTE"/>
		</method>
		<method name="WritePixelArray" result="ULONG">
			<arg name="srcRect" type="APTR"/>
			<arg name="SrcX" type="UWORD"/>
			<arg name="SrcY" type="UWORD"/>
			<arg name="SrcMod" type="UWORD"/>
			<arg name="RastPort" type="struct RastPort *"/>
			<arg name="DestX" type="UWORD"/>
			<arg name="DestY" type="UWORD"/>
			<arg name="SizeX" type="UWORD"/>
			<arg name="SizeY" type="UWORD"/>
			<arg name="SrcFormat" type="UBYTE"/>
		</method>
		<method name="MovePixelArray" result="ULONG">
			<arg name="SrcX" type="UWORD"/>
			<arg name="SrcY" type="UWORD"/>
			<arg name="RastPort" type="struct RastPort *"/>
			<arg name="DestX" type="UWORD"/>
			<arg name="DestY" type="UWORD"/>
			<arg name="SizeX" type="UWORD"/>
			<arg name="SizeY" type="UWORD"/>
		</method>
		<method name="Reserved6" result="void" status="unimplemented"/>
		<method name="InvertPixelArray" result="ULONG">
			<arg name="RastPort" type="struct RastPort *"/>
			<arg name="DestX" type="UWORD"/>
			<arg name="DestY" type="UWORD"/>
			<arg name="SizeX" type="UWORD"/>
			<arg name="SizeY" type="UWORD"/>
		</method>
		<method name="FillPixelArray" result="ULONG">
			<arg name="RastPort" type="struct RastPort *"/>
			<arg name="DestX" type="UWORD"/>
			<arg name="DestY" type="UWORD"/>
			<arg name="SizeX" type="UWORD"/>
			<arg name="SizeY" type="UWORD"/>
			<arg name="argb" type="ULONG"/>
		</method>
		<method name="DoCDrawMethodTagList" result="VOID">
			<arg name="hook" type="struct Hook *"/>
			<arg name="RastPort" type="struct RastPort *"/>
			<arg name="TagList" type="struct TagItem *"/>
		</method>
		<method name="DoCDrawMethodTags" result="VOID">
			<arg name="hook" type="struct Hook *"/>
			<arg name="RastPort" type="struct RastPort *"/>
			<vararg name="tag1" type="Tag"/>
		</method>
		<method name="CVideoCtrlTagList" result="VOID">
			<arg name="ViewPort" type="struct ViewPort *"/>
			<arg name="TagList" type="struct TagItem *"/>
		</method>
		<method name="CVideoCtrlTags" result="VOID">
			<arg name="ViewPort" type="struct ViewPort *"/>
			<vararg name="tag1" type="Tag"/>
		</method>
		<method name="LockBitMapTagList" result="APTR">
			<arg name="BitMap" type="APTR"/>
			<arg name="TagList" type="struct TagItem *"/>
		</method>
		<method name="LockBitMapTags" result="APTR">
			<arg name="BitMap" type="APTR"/>
			<vararg name="tag1" type="Tag"/>
		</method>
		<method name="UnLockBitMap" result="VOID">
			<arg name="Handle" type="APTR"/>
		</method>
		<method name="UnLockBitMapTagList" result="VOID">
			<arg name="Handle" type="APTR"/>
			<arg name="TagList" type="struct TagItem *"/>
		</method>
		<method name="UnLockBitMapTags" result="VOID">
			<arg name="Handle" type="APTR"/>
			<vararg name="tag1" type="Tag"/>
		</method>
		<method name="ExtractColor" result="ULONG">
			<arg name="RastPort" type="struct RastPort *"/>
			<arg name="BitMap" type="struct BitMap *"/>
			<arg name="Colour" type="ULONG"/>
			<arg name="SrcX" type="ULONG"/>
			<arg name="SrcY" type="ULONG"/>
			<arg name="Width" type="ULONG"/>
			<arg name="Height" type="ULONG"/>
		</method>
		<method name="Reserved7" result="void" status="unimplemented"/>
		<method name="WriteLUTPixelArray" result="ULONG">
			<arg name="srcRect" type="APTR"/>
			<arg name="SrcX" type="UWORD"/>
			<arg name="SrcY" type="UWORD"/>
			<arg name="SrcMod" type="UWORD"/>
			<arg name="RastPort" type="struct RastPort *"/>
			<arg name="ColorTab" type="APTR"/>
			<arg name="DestX" type="UWORD"/>
			<arg name="DestY" type="UWORD"/>
			<arg name="SizeX" type="UWORD"/>
			<arg name="SizeY" type="UWORD"/>
			<arg name="CTFormat" type="UBYTE"/>
		</method>
		<method name="Reserved8" result="void" status="unimplemented"/>
		<method name="Reserved9" result="void" status="unimplemented"/>
		<method name="WritePixelArrayAlpha" result="ULONG">
			<arg name="srcRect" type="APTR"/>
			<arg name="SrcX" type="UWORD"/>
			<arg name="SrcY" type="UWORD"/>
			<arg name="SrcMod" type="UWORD"/>
			<arg name="RastPort" type="struct RastPort *"/>
			<arg name="DestX" type="UWORD"/>
			<arg name="DestY" type="UWORD"/>
			<arg name="SizeX" type="UWORD"/>
			<arg name="SizeY" type="UWORD"/>
			<arg name="globalAlpha" type="ULONG"/>
		</method>
		<method name="BltTemplateAlpha" result="VOID">
			<arg name="srcTemplate" type="APTR"/>
			<arg name="SrcX" type="UWORD"/>
			<arg name="SrcY" type="UWORD"/>
			<arg name="RastPort" type="struct RastPort *"/>
			<arg name="DestX" type="UWORD"/>
			<arg name="DestY" type="UWORD"/>
			<arg name="SizeX" type="UWORD"/>
			<arg name="SizeY" type="UWORD"/>
		</method>
	</interface>
</library>
