=== sacredbanana/AmigaSDK-gcc/ppc-amigaos/SDK/include/interfaces/library.dtd
<?xml version="1.0" encoding="iso-8859-1"?>
<!ELEMENT library (include*, interface+)>
<!ATTLIST library
    basename    CDATA   #REQUIRED
    openname    CDATA   "none"
>

<!ELEMENT interface (description?, method+)>
<!ATTLIST interface
    name        CDATA   #REQUIRED
    version     CDATA   "1.0"
    flags       (protected|private|none) "none"
    struct	CDATA	#REQUIRED
    prefix	CDATA	"_impl_"
    asmprefix   CDATA   "none"
>

<!ELEMENT method (arg*,description?,vararg?)>
<!ATTLIST method
    name        CDATA   #REQUIRED
    result      CDATA   "void"
    status      CDATA   "implemented"
>

<!ELEMENT arg EMPTY>
<!ATTLIST arg
    name        CDATA   #REQUIRED
    type        CDATA   #REQUIRED
>

<!ELEMENT description (#PCDATA)>

<!ELEMENT include (#PCDATA)>

<!ELEMENT vararg EMPTY>
<!ATTLIST vararg
    name	CDATA   #REQUIRED
    type	CDATA	#REQUIRED
>

=== sacredbanana/AmigaSDK-gcc/ppc-amigaos/SDK/include/interfaces/usbfd.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE library SYSTEM "library.dtd">
<!-- autogenerated by fdtrans v50.9 -->
<library name="usbfd" basename="USBFDBase" openname="usbfd.library">
	<include>exec/types.h</include>
	<interface name="main" version="1.0" struct="USBFDIFace" prefix="_USBFD_" asmprefix="IUSBFD" global="IUSBFD">
		<method name="Obtain" result="ULONG"/>
		<method name="Release" result="ULONG"/>
		<method name="Expunge" result="void" status="unimplemented"/>
		<method name="Clone" result="struct Interface *" status="unimplemented"/>
		<method name="USBFDGetAttrsA" result="void">
			<arg name="taglist" type="struct TagItem *"/>
		</method>
		<method name="USBFDGetAttrs" result="void">
			<vararg name="taglist" type="ULONG"/>
		</method>
		<method name="USBFDRunFunction" result="LONG">
			<arg name="startmsg" type="struct USBFDStartupMsg *"/>
		</method>
		<method name="USBFDRunInterface" result="LONG">
			<arg name="startmsg" type="struct USBFDStartupMsg *"/>
		</method>
	</interface>
</library>

=== sacredbanana/AmigaSDK-gcc/amigaos4/sdk/ppc-amigaos/SDK/include/interfaces/label.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE library SYSTEM "library.dtd">
<library name="label" basename="LabelBase" openname="images/label.image">
	<include>intuition/intuition.h</include>
	<include>intuition/classes.h</include>
	<interface name="main" version="1.0" struct="LabelIFace" prefix="_Label_" asmprefix="ILabel" global="ILabel">
		<method name="Obtain" result="ULONG"/>
		<method name="Release" result="ULONG"/>
		<method name="Expunge" result="void" status="unimplemented"/>
		<method name="Clone" result="struct Interface *" status="unimplemented"/>
		<method name="LABEL_GetClass" result="Class *">
		</method>
	</interface>
</library>

=== sacredbanana/AmigaSDK-gcc/amigaos4/sdk/ppc-amigaos/SDK/include/interfaces/elf.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE library SYSTEM "library.dtd">
<library name="elf" basename="ElfBase" openname="elf.library">
  <include>libraries/elf.h</include>
  <include>utility/tagitem.h</include>

  <!-- Main Interface -->
  <interface name="main" version="1.0" struct="ElfIFace" prefix="_elf32_" asmprefix="IElf" global="IElf">
	<method name="Obtain" result="ULONG"/>
	<method name="Release" result="ULONG"/>
	<method name="Expunge" result="void" status="unimplemented"/>
	<method name="Clone" result="struct Interface *" status="unimplemented"/>

	<!-- Opening ELF files -->
	<method name="OpenElf" result="Elf32_Handle">
	  <arg name="taglist" type="struct TagItem *"/>
	</method>

	<method name="OpenElfTags" result="Elf32_Handle">
	  <vararg name="Tag" type="ULONG"/>
	</method>

	<method name="CloseElf" result="void">
	  <arg name="ElfHandle" type="Elf32_Handle"/>
	  <arg name="TagList" type="struct TagItem *"/>
	</method>

	<method name="CloseElfTags" result="void">
	  <arg name="ElfHandle" type="Elf32_Handle"/>
	  <vararg name="Tag" type="ULONG"/>
	</method>

	<!-- Getting elf sections and headers -->
	<method name="GetElfAttrs" result="ULONG">
	  <arg name="ElfHandle" type="Elf32_Handle"/>
	  <arg name="taglist" type="struct TagItem *"/>
	</method>

	<method name="GetElfAttrsTags" result="ULONG">
	  <arg name="ElfHandle" type="Elf32_Handle"/>
	  <vararg name="Tag" type="ULONG"/>
	</method>

	<method name="SetElfAttrs" result="ULONG">
	  <arg name="ElfHandle" type="Elf32_Handle"/>
	  <arg name="taglist" type="struct TagItem *"/>
	</method>

	<method name="SetElfAttrsTags" result="ULONG">
	  <arg name="ElfHandle" type="Elf32_Handle"/>
	  <vararg name="Tag" type="ULONG"/>
	</method>

	<method name="GetSectionHeader" result="Elf32_Shdr *">
	  <arg name="ElfHandle" type="Elf32_Handle"/>
	  <arg name="TagList" type="struct TagItem *"/>
	</method>

	<method name="GetSectionHeaderTags" result="Elf32_Shdr *">
	  <arg name="ElfHandle" type="Elf32_Handle"/>
	  <vararg name="Tag" type="ULONG"/>
	</method>

	<method name="GetSection" result="APTR">
	  <arg name="ElfHandle" type="Elf32_Handle"/>
	  <arg name="TagList" type="struct TagItem *"/>
	</method>

	<method name="GetSectionTags" result="APTR">
	  <arg name="ElfHandle" type="Elf32_Handle"/>
	  <vararg name="Tag" type="ULONG"/>
	</method>
	
	<!-- LoadSeg() an ELF file -->
	<method name="ElfLoadSeg" result="Elf32_Error">
	  <arg name="ElfHandle" type="Elf32_Handle"/>
	  <arg name="taglist" type="struct TagItem *"/>
	</method>

	<method name="ElfLoadSegTags" result="Elf32_Error">
	  <arg name="ElfHandle" type="Elf32_Handle"/>
	  <vararg name="Tag" type="ULONG"/>
	</method>

	<!-- Get a string from a string table -->
	<method name="GetElfString" result="CONST_STRPTR">
	  <arg name="ElfHandle" type="Elf32_Handle"/>
	  <arg name="SectionIndex" type="UWORD"/>
	  <arg name="StringIndex" type="UWORD"/>
	</method>

	<!-- Search for symbols -->
	<method name="SymbolQuery" result="ULONG">
	  <arg name="ElfHandle" type="Elf32_Handle"/>
	  <arg name="NumQueries" type="ULONG"/>
	  <arg name="Queries" type="struct Elf32_SymbolQuery *"/>
	</method>

	<!-- Unload a section -->
	<method name="UnloadSection" result="void">
	  <arg name="ElfHandle" type="Elf32_Handle"/>
	  <arg name="taglist" type="struct TagItem *"/>
	</method>

	<method name="UnloadSectionTags" result="void">
	  <arg name="ElfHandle" type="Elf32_Handle"/>
	  <vararg name="Tag" type="ULONG"/>
	</method>

    <!-- Map an address in an elf image to a section number -->
	<method name="AddressToSection" result="uint32">
	  <arg name="ElfHandle" type="Elf32_Handle"/>
	  <arg name="Address" type="APTR"/>
	</method>

	<!-- Scan all symbol tables in an ELF image using a hook -->
	<method name="ScanSymbolTable" result="void">
	  <arg name="ElfHandle" type="Elf32_Handle"/>
	  <arg name="hook" type="struct Hook *"/>
	  <arg name="tagList" type="struct TagItem *"/>
	</method>

	<method name="ScanSymbolTableTags" result="void">
	  <arg name="ElfHandle" type="Elf32_Handle"/>
	  <arg name="hook" type="struct Hook *"/>
	  <vararg name="Tag" type="ULONG"/>
	</method>

	<method name="RelocateSection" result="BOOL">
    	<arg name="ElfHandle" type="Elf32_Handle"/>
        <arg name="taglist" type="struct TagItem *"/>
    </method>

    <method name="RelocateSectionTags" result="BOOL">
    	<arg name="ElfHandle" type="Elf32_Handle"/>
        <vararg name="Tag" type="ULONG"/>
    </method>
    
    <method name="CopyDataSegment" result="void *">
    	<arg name="ElfHandle" type="Elf32_Handle"/>
    	<arg name="baseOffset" type="uint32 *"/>
    </method>
    
    <method name="FreeDataSegmentCopy" result="void">
    	<arg name="ElfHandle" type="Elf32_Handle"/>
    	<arg name="SegmentCopy" type="void *"/>
    </method>


    <method name="InitSHLibs" result="void">
	<arg name="ElfHandle" type="Elf32_Handle"/>
	<arg name="DoInit" type="BOOL"/>
    </method>

    <method name="DLOpen" result="APTR">
	<arg name="RootHandle" type="Elf32_Handle"/>
	<arg name="Name" type="CONST_STRPTR"/>
	<arg name="Flags" type="uint32"/>
    </method>

    <method name="DLClose" result="Elf32_Error">
	<arg name="RootHandle" type="Elf32_Handle"/>
	<arg name="Handle" type="APTR"/>
    </method>

    <method name="DLSym" result="Elf32_Error">
	<arg name="RootHandle" type="Elf32_Handle"/>
	<arg name="Handle" type="APTR"/>
	<arg name="SymbolName" type="CONST_STRPTR"/>
	<arg name="Result" type="APTR *"/>
    </method>

  </interface>
</library>

=== sacredbanana/AmigaSDK-gcc/amigaos4/sdk/ppc-amigaos/SDK/include/interfaces/bullet.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE library SYSTEM "library.dtd">
<!-- autogenerated by fdtrans v51.17 -->
<library name="bullet" basename="BulletBase" openname="bullet.library">
	<include>utility/tagitem.h</include>
	<include>diskfont/glyph.h</include>
	<interface name="main" version="1.0" struct="BulletIFace" prefix="_Bullet_" asmprefix="IBullet" global="IBullet">
		<method name="Obtain" result="ULONG"/>
		<method name="Release" result="ULONG"/>
		<method name="Expunge" result="void" status="unimplemented"/>
		<method name="Clone" result="struct Interface *" status="unimplemented"/>
		<method name="OpenEngine" result="struct GlyphEngine *">
		</method>
		<method name="CloseEngine" result="VOID">
			<arg name="glyphEngine" type="struct GlyphEngine *"/>
		</method>
		<method name="SetInfoA" result="ULONG">
			<arg name="glyphEngine" type="struct GlyphEngine *"/>
			<arg name="tagList" type="const struct TagItem *"/>
		</method>
		<method name="SetInfo" result="ULONG">
			<arg name="glyphEngine" type="struct GlyphEngine *"/>
			<vararg name="tag1" type="Tag"/>
		</method>
		<method name="ObtainInfoA" result="ULONG">
			<arg name="glyphEngine" type="struct GlyphEngine *"/>
			<arg name="tagList" type="const struct TagItem *"/>
		</method>
		<method name="ObtainInfo" result="ULONG">
			<arg name="glyphEngine" type="struct GlyphEngine *"/>
			<vararg name="tag1" type="Tag"/>
		</method>
		<method name="ReleaseInfoA" result="ULONG">
			<arg name="glyphEngine" type="struct GlyphEngine *"/>
			<arg name="tagList" type="const struct TagItem *"/>
		</method>
		<method name="ReleaseInfo" result="ULONG">
			<arg name="glyphEngine" type="struct GlyphEngine *"/>
			<vararg name="tag1" type="Tag"/>
		</method>
		<method name="GetGlyphMap" result="ULONG" status="private">
			<arg name="glyphEngine" type="struct GlyphEngine *"/>
			<arg name="glyphCode" type="ULONG"/>
			<arg name="glyphMap" type="struct GlyphMap **"/>
		</method>
	</interface>
</library>

=== sacredbanana/AmigaSDK-gcc/ppc-amigaos/SDK/include/interfaces/camd.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE library SYSTEM "library.dtd">
<library name="camd" basename="CamdBase" openname="camd.library">
<interface name="main" version="1.0" flags="protected" struct="CamdIFace" prefix="_camd_" global="ICamd">
<method name="Obtain" result="uint32"></method>
<method name="Release" result="uint32"></method>
<method name="Expunge" result="void" status="unimplemented"></method>
<method name="Clone" result="struct Interface *" status="unimplemented"></method>

<method name="LockCAMD" result="APTR">
	<arg name="locktype" type="uint32"/>
</method>

<method name="UnlockCAMD" result="void">
	<arg name="lock" type="APTR"/>
</method>

<method name="CreateMidiA" result="struct MidiNode *">
	<arg name="TagList" type="struct TagItem *"/>
</method>

<method name="CreateMidi" result="struct MidiNode *">
	<arg name="" type="..."/>
</method>

<method name="DeleteMidi" result="void">
	<arg name="mn" type="struct MidiNode *"/>
</method>

<method name="SetMidiAttrsA" result="BOOL">
	<arg name="mi" type="struct MidiNode *"/>
	<arg name="tags" type="struct TagItem *"/>
</method>

<method name="SetMidiAttrs" result="BOOL">
	<arg name="mi" type="struct MidiNode *"/>
	<arg name="" type="..."/>
</method>

<method name="GetMidiAttrsA" result="uint32">
	<arg name="mi" type="struct MidiNode *"/>
	<arg name="attrs" type="struct TagItem *"/>
</method>

<method name="GetMidiAttrs" result="uint32">
	<arg name="mi" type="struct MidiNode *"/>
	<arg name="" type="..."/>
</method>

<method name="NextMidi" result="struct MidiNode *">
	<arg name="last" type="struct MidiNode *"/>
</method>

<method name="FindMidi" result="struct MidiNode *">
	<arg name="name" type="STRPTR"/>
</method>

<method name="FlushMidi" result="void">
	<arg name="mi" type="struct MidiNode *"/>
</method>

<method name="AddMidiLinkA" result="struct MidiLink *">
	<arg name="mi" type="struct MidiNode *"/>
	<arg name="type" type="int32"/>
	<arg name="TagsList" type="struct TagItem *"/>
</method>

<method name="AddMidiLink" result="struct MidiLink *">
	<arg name="mi" type="struct MidiNode *"/>
	<arg name="type" type="int32"/>
	<arg name="" type="..."/>
</method>

<method name="RemoveMidiLink" result="void">
	<arg name="ml" type="struct MidiLink *"/>
</method>

<method name="SetMidiLinkAttrsA" result="BOOL">
	<arg name="ml" type="struct MidiLink *"/>
	<arg name="tags" type="struct TagItem *"/>
</method>

<method name="SetMidiLinkAttrs" result="BOOL">
	<arg name="ml" type="struct MidiLink *"/>
	<arg name="" type="..."/>
</method>

<method name="GetMidiLinkAttrsA" result="uint32">
	<arg name="ml" type="struct MidiLink *"/>
	<arg name="attrs" type="struct TagItem *"/>
</method>

<method name="GetMidiLinkAttrs" result="uint32">
	<arg name="ml" type="struct MidiLink *"/>
	<arg name="" type="..."/>
</method>

<method name="NextClusterLink" result="struct MidiLink *">
	<arg name="mc" type="struct MidiCluster *"/>
	<arg name="last" type="struct MidiLink *"/>
	<arg name="type" type="int32"/>
</method>

<method name="NextMidiLink" result="struct MidiLink *">
	<arg name="mi" type="struct MidiNode *"/>
	<arg name="last" type="struct MidiLink *"/>
	<arg name="type" type="int32"/>
</method>

<method name="MidiLinkConnected" result="BOOL">
	<arg name="ml" type="struct MidiLink *"/>
</method>

<method name="NextCluster" result="struct MidiCluster *">
	<arg name="last" type="struct MidiCluster *"/>
</method>

<method name="FindCluster" result="struct MidiCluster *">
	<arg name="name" type="STRPTR"/>
</method>

<method name="PutMidi" result="void">
	<arg name="link" type="struct MidiLink *"/>
	<arg name="Msg" type="uint32"/>
</method>

<method name="GetMidi" result="BOOL">
	<arg name="mn" type="struct MidiNode *"/>
	<arg name="msg" type="MidiMsg *"/>
</method>

<method name="WaitMidi" result="BOOL">
	<arg name="mn" type="struct MidiNode *"/>
	<arg name="msg" type="MidiMsg *"/>
</method>

<method name="PutSysEx" result="void">
	<arg name="ml" type="struct MidiLink *"/>
	<arg name="Buffer" type="uint8 *"/>
</method>

<method name="GetSysEx" result="uint32">
	<arg name="mn" type="struct MidiNode *"/>
	<arg name="Buf" type="uint8 *"/>
	<arg name="Len" type="uint32"/>
</method>

<method name="QuerySysEx" result="uint32">
	<arg name="mn" type="struct MidiNode *"/>
</method>

<method name="SkipSysEx" result="void">
	<arg name="mn" type="struct MidiNode *"/>
</method>

<method name="GetMidiErr" result="uint8">
	<arg name="mn" type="struct MidiNode *"/>
</method>

<method name="MidiMsgType" result="int16">
	<arg name="Msg" type="MidiMsg *"/>
</method>

<method name="MidiMsgLen" result="int16">
	<arg name="StatusByte" type="uint32"/>
</method>

<method name="ParseMidi" result="void">
	<arg name="ml" type="struct MidiLink *"/>
	<arg name="Buffer" type="CONST uint8 *"/>
	<arg name="Length" type="uint32"/>
</method>

<method name="OpenMidiDevice" result="struct MidiDeviceData *">
	<arg name="Name" type="STRPTR"/>
</method>

<method name="CloseMidiDevice" result="void">
	<arg name="MidiDeviceData" type="struct MidiDeviceData *"/>
</method>

<method name="RethinkCAMD" result="int32">
</method>

<method name="StartClusterNotify" result="void">
	<arg name="cn" type="struct ClusterNotifyNode *"/>
</method>

<method name="EndClusterNotify" result="void">
	<arg name="cn" type="struct ClusterNotifyNode *"/>
</method>

</interface>
</library>

=== sacredbanana/AmigaSDK-gcc/amigaos4/sdk/ppc-amigaos/SDK/include/interfaces/catweasel.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE library SYSTEM "library.dtd">
<library name="catweasel" basename="CWBase" openname="catweasel.resource" basetype="CWBase">
  <include>exec/types.h</include>
  <include>proto/expansion.h</include>
  <include>expansion/pci.h</include>
  <include>resources/catweasel.h</include>
  <interface name="main" version="1.0" struct="CWIFace" prefix="_CW_" asmprefix="ICW" global="ICW">
		<method name="Obtain" result="ULONG"/>
		<method name="Release" result="ULONG"/>
		<method name="Expunge" result="void" status="unimplemented"/>
		<method name="Clone" result="struct Interface *" status="unimplemented"/>
		<method name="CW3Present" result="BOOL">
		</method>
		<method name="CW4Present" result="BOOL">
		</method>
	  <method name="CW3GameportAvail" result="BOOL">
		</method>
		<method name="CW3KeyboardAvail" result="BOOL">
		</method>
	  <method name="CW3SIDAvail" result="BOOL">
	  </method>
	  <method name="CW3FloppyAvail" result="BOOL">
	  </method>
  </interface>
  <interface name="cw3gameport" version="1.0" struct="CW3GameportIFace" prefix="_CW3Gameport_" asmprefix="ICW3Gameport" global="ICW3Gameport">
    <method name="Obtain" result="ULONG"/>
    <method name="Release" result="ULONG"/>
    <method name="Expunge" result="void" status="unimplemented"/>
    <method name="Clone" result="struct Interface *" status="unimplemented"/>
    <method name="InByte" result="UBYTE">
      <arg name="offset" type="ULONG"/>
    </method>
    <method name="OutByte" result="void">
      <arg name="offset" type="ULONG"/>
      <arg name="value" type="UBYTE"/>
    </method>
  </interface> 
  <interface name="cw3keyboard" version="1.0" struct="CW3KeyboardIFace" prefix="_CW3Keyboard_" asmprefix="ICW3Keyboard" global="ICW3Keyboard">
    <method name="Obtain" result="ULONG"/>
    <method name="Release" result="ULONG"/>
    <method name="Expunge" result="void" status="unimplemented"/>
    <method name="Clone" result="struct Interface *" status="unimplemented"/>
    <method name="InByte" result="UBYTE">
      <arg name="offset" type="ULONG"/>
    </method>
    <method name="OutByte" result="void">
      <arg name="offset" type="ULONG"/>
      <arg name="value" type="UBYTE"/>
    </method>
  </interface> 
  <interface name="cw3sid" version="1.0" struct="CW3SIDIFace" prefix="_CW3SID_" asmprefix="ICW3SID" global="ICW3SID">
    <method name="Obtain" result="ULONG"/>
    <method name="Release" result="ULONG"/>
    <method name="Expunge" result="void" status="unimplemented"/>
    <method name="Clone" result="struct Interface *" status="unimplemented"/>
    <method name="InByte" result="UBYTE">
      <arg name="offset" type="ULONG"/>
    </method>
    <method name="OutByte" result="void">
      <arg name="offset" type="ULONG"/>
      <arg name="value" type="UBYTE"/>
    </method>
  </interface> 
  <interface name="cw3floppy" version="1.0" struct="CW3FloppyIFace" prefix="_CW3Floppy_" asmprefix="ICW3Floppy" global="ICW3Floppy">
    <method name="Obtain" result="ULONG"/>
    <method name="Release" result="ULONG"/>
    <method name="Expunge" result="void" status="unimplemented"/>
    <method name="Clone" result="struct Interface *" status="unimplemented"/>
    <method name="InByte" result="UBYTE">
      <arg name="offset" type="ULONG"/>
    </method>
    <method name="OutByte" result="void">
      <arg name="offset" type="ULONG"/>
      <arg name="value" type="UBYTE"/>
    </method>
  </interface> 
</library>

=== sacredbanana/AmigaSDK-gcc/amigaos4/sdk/ppc-amigaos/SDK/include/interfaces/nonvolatile.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE library SYSTEM "library.dtd">
<!-- autogenerated by fdtrans v51.22 -->
<library name="nonvolatile" basename="NVBase" openname="nonvolatile.library">
	<include>exec/types.h</include>
	<include>exec/lists.h</include>
	<include>libraries/nonvolatile.h</include>
	<interface name="main" version="1.0" struct="NVIFace" prefix="_NV_" asmprefix="INV" global="INV">
		<method name="Obtain" result="uint32"/>
		<method name="Release" result="uint32"/>
		<method name="Expunge" result="void" status="unimplemented"/>
		<method name="Clone" result="struct Interface *" status="unimplemented"/>
		<method name="GetCopyNV" result="APTR">
			<arg name="appName" type="CONST_STRPTR"/>
			<arg name="itemName" type="CONST_STRPTR"/>
			<arg name="killRequesters" type="BOOL"/>
		</method>
		<method name="FreeNVData" result="VOID">
			<arg name="data" type="APTR"/>
		</method>
		<method name="StoreNV" result="UWORD">
			<arg name="appName" type="CONST_STRPTR"/>
			<arg name="itemName" type="CONST_STRPTR"/>
			<arg name="data" type="const APTR"/>
			<arg name="length" type="ULONG"/>
			<arg name="killRequesters" type="BOOL"/>
		</method>
		<method name="DeleteNV" result="BOOL">
			<arg name="appName" type="CONST_STRPTR"/>
			<arg name="itemName" type="CONST_STRPTR"/>
			<arg name="killRequesters" type="BOOL"/>
		</method>
		<method name="GetNVInfo" result="struct NVInfo *">
			<arg name="killRequesters" type="BOOL"/>
		</method>
		<method name="GetNVList" result="struct MinList *">
			<arg name="appName" type="CONST_STRPTR"/>
			<arg name="killRequesters" type="BOOL"/>
		</method>
		<method name="SetNVProtection" result="BOOL">
			<arg name="appName" type="CONST_STRPTR"/>
			<arg name="itemName" type="CONST_STRPTR"/>
			<arg name="mask" type="LONG"/>
			<arg name="killRequesters" type="BOOL"/>
		</method>
		<method name="SetUBootVar" result="ULONG">
			<arg name="name" type="CONST_STRPTR"/>
			<arg name="value" type="CONST_STRPTR"/>
		</method>
		<method name="GetUBootVar" result="CONST_STRPTR">
			<arg name="name" type="CONST_STRPTR"/>
		</method>
		<method name="FreeUBootVar" result="void">
			<arg name="value" type="CONST_STRPTR"/>
		</method>
	</interface>
</library>

=== sacredbanana/AmigaSDK-gcc/amigaos4/sdk/ppc-amigaos/SDK/include/interfaces/performancemonitor.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE library SYSTEM "library.dtd">
<library name="performancemonitor" basename="PMBase" openname="performancemonitor.resource">

  <copyright>Copyright (C) 2004 Trevor Dickinson</copyright>

  <include>interfaces/performancemonitor.h</include>
  <include>resources/performancemonitor.h</include>

  <interface name="main" version="1.0" struct="PerformanceMonitorIFace" prefix="main" asmprefix="IPM" global="IPM">
    <method name="Obtain" result="uint32"/>
    <method name="Release" result="uint32"/>
    <method name="Expunge" result="void" status="unimplemented"/>
    <method name="Clone" result="struct Interface *" status="unimplemented"/>

    <method name="CounterGet" result="uint32">
      <arg name="whatCount" type="uint32"/>
    </method>

    <method name="CounterMatch" result="uint32">
      <arg name="itemNum" type="uint32"/>
    </method>

    <method name="CounterControl" result="BOOL">
      <arg name="whichCount" type="uint32"/>
      <arg name="value" type="int32"/>
      <arg name="what" type="uint32"/>
    </method>

    <method name="EventControl" result="uint32">
      <arg name="tagList" type="struct TagItem *"/>
    </method>

    <method name="EventControlTags" result="uint32">
      <vararg name="Tag1" type="uint32"/>
    </method>

    <method name="SetInterruptVector" result="struct Interrupt *">
      <arg name="event" type="uint32"/>
      <arg name="handler" type="struct Interrupt *"/>
    </method>

    <method name="Mark" result="void">
      <arg name="task" type="struct Task *"/>
    </method>

    <method name="Unmark" result="void">
      <arg name="task" type="struct Task *"/>
    </method>

    <method name="MonitorControl" result="uint32">
      <arg name="tagList" type="struct TagItem *"/>
    </method>

    <method name="MonitorControlTags" result="uint32">
      <vararg name="Tag1" type="uint32"/>
    </method>

    <method name="Query" result="uint32">
      <arg name="item" type="uint32"/>
    </method>

    <method name="SetSampledAddress" result="void">
      <arg name="addr" type="APTR"/>
    </method>

    <method name="GetSampledAddress" result="APTR">
    </method>

    <method name="SetBreakpoint" result="void">
      <arg name="type" type="uint32"/>
      <arg name="instAddr" type="APTR"/>
      <arg name="instMask" type="uint32"/>
      <arg name="except" type="BOOL"/>
    </method>
  </interface>
</library>
