=== sacredbanana/AmigaSDK-gcc/ppc-amigaos/SDK/include/interfaces/library.dtd
<?xml version="1.0" encoding="iso-8859-1"?>
<!ELEMENT library (include*, interface+)>
<!ATTLIST library
    basename    CDATA   #REQUIRED
    openname    CDATA   "none"
>

<!ELEMENT interface (description?, method+)>
<!ATTLIST interface
    name        CDATA   #REQUIRED
    version     CDATA   "1.0"
    flags       (protected|private|none) "none"
    struct	CDATA	#REQUIRED
    prefix	CDATA	"_impl_"
    asmprefix   CDATA   "none"
>

<!ELEMENT method (arg*,description?,vararg?)>
<!ATTLIST method
    name        CDATA   #REQUIRED
    result      CDATA   "void"
    status      CDATA   "implemented"
>

<!ELEMENT arg EMPTY>
<!ATTLIST arg
    name        CDATA   #REQUIRED
    type        CDATA   #REQUIRED
>

<!ELEMENT description (#PCDATA)>

<!ELEMENT include (#PCDATA)>

<!ELEMENT vararg EMPTY>
<!ATTLIST vararg
    name	CDATA   #REQUIRED
    type	CDATA	#REQUIRED
>

=== sacredbanana/AmigaSDK-gcc/amigaos4/sdk/ppc-amigaos/SDK/include/interfaces/filler.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE library SYSTEM "library.dtd">
<library name="filler" basename="FillerBase" openname="images/filler.image">
	<include>intuition/intuition.h</include>
	<include>intuition/classes.h</include>
	<interface name="main" version="1.0" struct="FillerIFace" prefix="_Filler_" asmprefix="IFiller" global="IFiller">
		<method name="Obtain" result="ULONG"/>
		<method name="Release" result="ULONG"/>
		<method name="Expunge" result="void" status="unimplemented"/>
		<method name="Clone" result="struct Interface *" status="unimplemented"/>
		<method name="FILLER_GetClass" result="Class *">
		</method>
	</interface>
</library>

=== sacredbanana/AmigaSDK-gcc/amigaos4/sdk/ppc-amigaos/SDK/include/interfaces/screenblanker.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE library SYSTEM "library.dtd">
<library name="screenblanker" basename="ScreenBlanker" openname="screenblanker.library">
<include>exec/libraries.h</include>
<include>proto/blankermodule.h</include>

<!-- The main interface which allows to make new screenblanker-instances -->
	<interface name="main" version="1.0" struct="ScreenBlankerIFace" prefix="_screenblanker_" asmprefix="IScreenBlanker" global="IScreenBlanker">

		<method name="Obtain" result="uint32">
		</method>
		
		<method name="Release" result="uint32">
		</method>
		
		<method name="Expunge" result="void" status="unimplemented">
		</method>
		
		<method name="Clone" result="struct IScreenBlanker *">
		</method>
		
		<method name="OpenBlankerModuleA" result="BOOL">
			<arg name="name" type="CONST_STRPTR"/>
			<arg name="tags" type="struct TagItem *"/>
		</method>
		
		<method name="OpenBlankerModule" result="BOOL">
			<arg name="name" type="CONST_STRPTR"/>
			<vararg name="tag1" type="Tag"/>
		</method>
		
		<method name="CloseBlankerModule" result="void"/>
		
		<method name="SetBlankingMode" result="BOOL">
			<arg name="mode" type="uint32"/>
		</method>
		
		<method name="SetScreenBlankerAttrsA" result="uint32">
			<arg name="tags" type="struct TagItem *"/>
		</method>
		
		<method name="SetScreenBlankerAttrs" result="uint32">
			<vararg name="tag1" type="Tag"/>
		</method>
		
		<method name="GetScreenBlankerAttrsA" result="uint32">
			<arg name="tags" type="struct TagItem *"/>
		</method>
		
		<method name="GetScreenBlankerAttrs" result="uint32">
			<vararg name="tag1" type="Tag"/>
		</method>

		<method name="LogPuts" result="void">
			<arg name="err" type="int32"/>
			<arg name="context" type="CONST_STRPTR"/>
			<arg name="msg" type="CONST_STRPTR"/>
		</method>

		<method name="LogFmtA" result="uint32">
			<arg name="err" type="int32"/>
			<arg name="context" type="CONST_STRPTR"/>
			<arg name="msg" type="CONST_STRPTR"/>
			<arg name="args" type="uint32 *"/>
		</method>

		<method name="LogFmt" result="uint32">
			<arg name="err" type="int32"/>
			<arg name="context" type="CONST_STRPTR"/>
			<arg name="msg" type="CONST_STRPTR"/>
			<vararg name="tag1" type="Tag"/>
		</method>

	</interface>

</library>

=== sacredbanana/AmigaSDK-gcc/ppc-amigaos/SDK/include/interfaces/amigaguide.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE library SYSTEM "library.dtd">
<!-- autogenerated by fdtrans v51.22 -->
<library name="amigaguide" basename="AmigaGuideBase" openname="amigaguide.library">
	<include>exec/types.h</include>
	<include>exec/ports.h</include>
	<include>dos/dos.h</include>
	<include>libraries/amigaguide.h</include>
	<include>utility/tagitem.h</include>
	<include>utility/hooks.h</include>
	<include>rexx/storage.h</include>
	<interface name="main" version="1.0" struct="AmigaGuideIFace" prefix="_AmigaGuide_" asmprefix="IAmigaGuide" global="IAmigaGuide">
		<method name="Obtain" result="uint32"/>
		<method name="Release" result="uint32"/>
		<method name="Expunge" result="void" status="unimplemented"/>
		<method name="Clone" result="struct Interface *" status="unimplemented"/>
		<method name="AGARexxHost" result="LONG" status="private">
			<arg name="rmsg" type="struct RexxMsg *"/>
			<arg name="result" type="STRPTR *"/>
		</method>
		<method name="LockAmigaGuideBase" result="LONG">
			<arg name="handle" type="APTR"/>
		</method>
		<method name="UnlockAmigaGuideBase" result="VOID">
			<arg name="key" type="LONG"/>
		</method>
		<method name="ExpungeDataBases" result="VOID" status="private">
			<arg name="flush" type="BOOL"/>
		</method>
		<method name="OpenAmigaGuideA" result="APTR">
			<arg name="nag" type="struct NewAmigaGuide *"/>
			<arg name="tags" type="struct TagItem *"/>
		</method>
		<method name="OpenAmigaGuide" result="APTR">
			<arg name="nag" type="struct NewAmigaGuide *"/>
			<vararg name="tag1" type="Tag"/>
		</method>
		<method name="OpenAmigaGuideAsyncA" result="APTR">
			<arg name="nag" type="struct NewAmigaGuide *"/>
			<arg name="attrs" type="struct TagItem *"/>
		</method>
		<method name="OpenAmigaGuideAsync" result="APTR">
			<arg name="nag" type="struct NewAmigaGuide *"/>
			<vararg name="tag1" type="Tag"/>
		</method>
		<method name="CloseAmigaGuide" result="VOID">
			<arg name="cl" type="APTR"/>
		</method>
		<method name="AmigaGuideSignal" result="ULONG">
			<arg name="cl" type="APTR"/>
		</method>
		<method name="GetAmigaGuideMsg" result="struct AmigaGuideMsg *">
			<arg name="cl" type="APTR"/>
		</method>
		<method name="ReplyAmigaGuideMsg" result="VOID">
			<arg name="amsg" type="struct AmigaGuideMsg *"/>
		</method>
		<method name="SetAmigaGuideContextA" result="LONG">
			<arg name="cl" type="APTR"/>
			<arg name="id" type="ULONG"/>
			<arg name="attrs" type="struct TagItem *"/>
		</method>
		<method name="SetAmigaGuideContext" result="LONG">
			<arg name="cl" type="APTR"/>
			<arg name="id" type="ULONG"/>
			<vararg name="tag1" type="Tag"/>
		</method>
		<method name="SendAmigaGuideContextA" result="LONG">
			<arg name="cl" type="APTR"/>
			<arg name="attrs" type="struct TagItem *"/>
		</method>
		<method name="SendAmigaGuideContext" result="LONG">
			<arg name="cl" type="APTR"/>
			<vararg name="tag1" type="Tag"/>
		</method>
		<method name="SendAmigaGuideCmdA" result="LONG">
			<arg name="cl" type="APTR"/>
			<arg name="cmd" type="STRPTR"/>
			<arg name="attrs" type="struct TagItem *"/>
		</method>
		<method name="SendAmigaGuideCmd" result="LONG">
			<arg name="cl" type="APTR"/>
			<arg name="cmd" type="STRPTR"/>
			<vararg name="tag1" type="Tag"/>
		</method>
		<method name="SetAmigaGuideAttrsA" result="LONG">
			<arg name="cl" type="APTR"/>
			<arg name="attrs" type="struct TagItem *"/>
		</method>
		<method name="SetAmigaGuideAttrs" result="LONG">
			<arg name="cl" type="APTR"/>
			<vararg name="tag1" type="Tag"/>
		</method>
		<method name="GetAmigaGuideAttr" result="LONG">
			<arg name="tag" type="Tag"/>
			<arg name="cl" type="APTR"/>
			<arg name="storage" type="ULONG *"/>
		</method>
		<method name="SetAmigaGuideHook" result="LONG" status="private">
			<arg name="cl" type="APTR"/>
			<arg name="v1" type="ULONG"/>
			<arg name="v2" type="ULONG"/>
			<arg name="v3" type="ULONG"/>
		</method>
		<method name="LoadXRef" result="LONG">
			<arg name="lock" type="BPTR"/>
			<arg name="name" type="STRPTR"/>
		</method>
		<method name="ExpungeXRef" result="VOID">
		</method>
		<method name="AddAmigaGuideHostA" result="APTR">
			<arg name="h" type="struct Hook *"/>
			<arg name="name" type="STRPTR"/>
			<arg name="attrs" type="struct TagItem *"/>
		</method>
		<method name="AddAmigaGuideHost" result="APTR">
			<arg name="h" type="struct Hook *"/>
			<arg name="name" type="STRPTR"/>
			<vararg name="tag1" type="Tag"/>
		</method>
		<method name="RemoveAmigaGuideHostA" result="LONG">
			<arg name="hh" type="APTR"/>
			<arg name="attrs" type="struct TagItem *"/>
		</method>
		<method name="RemoveAmigaGuideHost" result="LONG">
			<arg name="hh" type="APTR"/>
			<vararg name="tag1" type="Tag"/>
		</method>
		<method name="OpenE" result="BPTR" status="private">
			<arg name="path" type="BPTR"/>
			<arg name="name" type="STRPTR"/>
			<arg name="mode" type="LONG"/>
		</method>
		<method name="LockE" result="BPTR" status="private">
			<arg name="path" type="BPTR"/>
			<arg name="name" type="STRPTR"/>
			<arg name="mode" type="LONG"/>
		</method>
		<method name="CopyPathList" result="BPTR" status="private">
			<arg name="path" type="BPTR"/>
		</method>
		<method name="AddPathEntries" result="BPTR" status="private">
			<arg name="path" type="BPTR"/>
			<arg name="argptr" type="STRPTR *"/>
		</method>
		<method name="FreePathList" result="VOID" status="private">
			<arg name="path" type="BPTR"/>
		</method>
		<method name="ParsePathString" result="ULONG" status="private">
			<arg name="line" type="STRPTR"/>
			<arg name="argv" type="STRPTR *"/>
			<arg name="max" type="ULONG"/>
		</method>
		<method name="OpenDataBase" result="struct DataBase *" status="private">
			<arg name="lock" type="BPTR"/>
			<arg name="name" type="STRPTR"/>
		</method>
		<method name="LoadNode" result="LONG" status="private">
			<arg name="cl" type="APTR"/>
			<arg name="db" type="struct DataBase *"/>
			<arg name="hn" type="struct HelpNode *"/>
		</method>
		<method name="UnloadNode" result="LONG" status="private">
			<arg name="cl" type="APTR"/>
			<arg name="db" type="struct DataBase *"/>
			<arg name="hn" type="struct HelpNode *"/>
		</method>
		<method name="CloseDataBase" result="LONG" status="private">
			<arg name="db" type="struct DataBase *"/>
		</method>
		<method name="GetAmigaGuideString" result="CONST_STRPTR">
			<arg name="id" type="LONG"/>
		</method>
	</interface>
</library>

=== sacredbanana/AmigaSDK-gcc/amigaos4/sdk/ppc-amigaos/SDK/include/interfaces/window.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE library SYSTEM "library.dtd">
<library name="window" basename="WindowBase" classname="WindowClass" openname="window.class">
	<include>intuition/intuition.h</include>
	<include>intuition/classes.h</include>
	<interface name="main" version="1.0" struct="WindowIFace" prefix="_Window_" asmprefix="IWindow" global="IWindow">
		<method name="Obtain" result="ULONG"/>
		<method name="Release" result="ULONG"/>
		<method name="Expunge" result="void" status="unimplemented"/>
		<method name="Clone" result="struct Interface *" status="unimplemented"/>
		<method name="WINDOW_GetClass" result="Class *">
		</method>
		<method name="NewWindowPrefs" result="void">
		</method>
		<method name="WindowPrivate1" result="ULONG">
		</method>
		<method name="UpdateWindowPrefs" result="void">
			<arg name="screen" type="struct Screen *"/>
		</method>
	</interface>
</library>

=== sacredbanana/AmigaSDK-gcc/ppc-amigaos/SDK/include/interfaces/gadtools.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE library SYSTEM "library.dtd">
<!-- autogenerated by fdtrans v50.8 -->
<library name="gadtools" basename="GadToolsBase" openname="gadtools.library">
	<include>exec/libraries.h</include>
	<include>intuition/intuition.h</include>
	<include>utility/tagitem.h</include>
	<include>libraries/gadtools.h</include>
	<interface name="main" version="1.0" struct="GadToolsIFace" prefix="_GadTools_" asmprefix="IGadTools" global="IGadTools">
		<method name="Obtain" result="ULONG"/>
		<method name="Release" result="ULONG"/>
		<method name="Expunge" result="void" status="unimplemented"/>
		<method name="Clone" result="struct Interface *" status="unimplemented"/>
		<method name="CreateGadgetA" result="struct Gadget *">
			<arg name="kind" type="ULONG"/>
			<arg name="gad" type="struct Gadget *"/>
			<arg name="ng" type="const struct NewGadget *"/>
			<arg name="taglist" type="const struct TagItem *"/>
		</method>
		<method name="CreateGadget" result="struct Gadget *">
			<arg name="kind" type="ULONG"/>
			<arg name="gad" type="struct Gadget *"/>
			<arg name="ng" type="const struct NewGadget *"/>
			<vararg name="tag1" type="Tag"/>
		</method>
		<method name="FreeGadgets" result="VOID">
			<arg name="gad" type="struct Gadget *"/>
		</method>
		<method name="GT_SetGadgetAttrsA" result="VOID">
			<arg name="gad" type="struct Gadget *"/>
			<arg name="win" type="struct Window *"/>
			<arg name="req" type="struct Requester *"/>
			<arg name="taglist" type="const struct TagItem *"/>
		</method>
		<method name="GT_SetGadgetAttrs" result="VOID">
			<arg name="gad" type="struct Gadget *"/>
			<arg name="win" type="struct Window *"/>
			<arg name="req" type="struct Requester *"/>
			<vararg name="tag1" type="Tag"/>
		</method>
		<method name="CreateMenusA" result="struct Menu *">
			<arg name="newmenu" type="const struct NewMenu *"/>
			<arg name="taglist" type="const struct TagItem *"/>
		</method>
		<method name="CreateMenus" result="struct Menu *">
			<arg name="newmenu" type="const struct NewMenu *"/>
			<vararg name="tag1" type="Tag"/>
		</method>
		<method name="FreeMenus" result="VOID">
			<arg name="menu" type="struct Menu *"/>
		</method>
		<method name="LayoutMenuItemsA" result="BOOL">
			<arg name="firstitem" type="struct MenuItem *"/>
			<arg name="vi" type="APTR"/>
			<arg name="taglist" type="const struct TagItem *"/>
		</method>
		<method name="LayoutMenuItems" result="BOOL">
			<arg name="firstitem" type="struct MenuItem *"/>
			<arg name="vi" type="APTR"/>
			<vararg name="tag1" type="Tag"/>
		</method>
		<method name="LayoutMenusA" result="BOOL">
			<arg name="firstmenu" type="struct Menu *"/>
			<arg name="vi" type="APTR"/>
			<arg name="taglist" type="const struct TagItem *"/>
		</method>
		<method name="LayoutMenus" result="BOOL">
			<arg name="firstmenu" type="struct Menu *"/>
			<arg name="vi" type="APTR"/>
			<vararg name="tag1" type="Tag"/>
		</method>
		<method name="GT_GetIMsg" result="struct IntuiMessage *">
			<arg name="iport" type="struct MsgPort *"/>
		</method>
		<method name="GT_ReplyIMsg" result="VOID">
			<arg name="imsg" type="struct IntuiMessage *"/>
		</method>
		<method name="GT_RefreshWindow" result="VOID">
			<arg name="win" type="struct Window *"/>
			<arg name="req" type="struct Requester *"/>
		</method>
		<method name="GT_BeginRefresh" result="VOID">
			<arg name="win" type="struct Window *"/>
		</method>
		<method name="GT_EndRefresh" result="VOID">
			<arg name="win" type="struct Window *"/>
			<arg name="complete" type="BOOL"/>
		</method>
		<method name="GT_FilterIMsg" result="struct IntuiMessage *">
			<arg name="imsg" type="const struct IntuiMessage *"/>
		</method>
		<method name="GT_PostFilterIMsg" result="struct IntuiMessage *">
			<arg name="imsg" type="struct IntuiMessage *"/>
		</method>
		<method name="CreateContext" result="struct Gadget *">
			<arg name="glistptr" type="struct Gadget **"/>
		</method>
		<method name="DrawBevelBoxA" result="VOID">
			<arg name="rport" type="struct RastPort *"/>
			<arg name="left" type="WORD"/>
			<arg name="top" type="WORD"/>
			<arg name="width" type="WORD"/>
			<arg name="height" type="WORD"/>
			<arg name="taglist" type="const struct TagItem *"/>
		</method>
		<method name="DrawBevelBox" result="VOID">
			<arg name="rport" type="struct RastPort *"/>
			<arg name="left" type="WORD"/>
			<arg name="top" type="WORD"/>
			<arg name="width" type="WORD"/>
			<arg name="height" type="WORD"/>
			<vararg name="tag1" type="Tag"/>
		</method>
		<method name="GetVisualInfoA" result="APTR">
			<arg name="screen" type="struct Screen *"/>
			<arg name="taglist" type="const struct TagItem *"/>
		</method>
		<method name="GetVisualInfo" result="APTR">
			<arg name="screen" type="struct Screen *"/>
			<vararg name="tag1" type="Tag"/>
		</method>
		<method name="FreeVisualInfo" result="VOID">
			<arg name="vi" type="APTR"/>
		</method>
		<method name="GTReserved0" result="VOID" status="private">
		</method>
		<method name="GTReserved1" result="VOID" status="private">
		</method>
		<method name="GTReserved2" result="VOID" status="private">
		</method>
		<method name="GTReserved3" result="VOID" status="private">
		</method>
		<method name="GTReserved4" result="VOID" status="private">
		</method>
		<method name="GTReserved5" result="VOID" status="private">
		</method>
		<method name="GT_GetGadgetAttrsA" result="LONG">
			<arg name="gad" type="struct Gadget *"/>
			<arg name="win" type="struct Window *"/>
			<arg name="req" type="struct Requester *"/>
			<arg name="taglist" type="const struct TagItem *"/>
		</method>
		<method name="GT_GetGadgetAttrs" result="LONG">
			<arg name="gad" type="struct Gadget *"/>
			<arg name="win" type="struct Window *"/>
			<arg name="req" type="struct Requester *"/>
			<vararg name="tag1" type="Tag"/>
		</method>
	</interface>
</library>

=== sacredbanana/AmigaSDK-gcc/ppc-amigaos/SDK/include/interfaces/resource.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE library SYSTEM "library.dtd">
<!-- autogenerated by fdtrans v50.9 -->
<library name="resource" basename="ResourceBase" openname="resource.library">
	<include>libraries/resource.h</include>
	<include>intuition/classusr.h</include>
	<include>intuition/intuition.h</include>
	<include>libraries/locale.h</include>
	<include>utility/tagitem.h</include>
	<interface name="main" version="1.0" struct="ResourceIFace" prefix="_Resource_" asmprefix="IResource" global="IResource">
		<method name="Obtain" result="ULONG"/>
		<method name="Release" result="ULONG"/>
		<method name="Expunge" result="void" status="unimplemented"/>
		<method name="Clone" result="struct Interface *" status="unimplemented"/>
		<method name="RL_OpenResource" result="RESOURCEFILE">
			<arg name="resource" type="APTR"/>
			<arg name="screen" type="struct Screen *"/>
			<arg name="catalog" type="struct Catalog *"/>
		</method>
		<method name="RL_CloseResource" result="VOID">
			<arg name="resfile" type="RESOURCEFILE"/>
		</method>
		<method name="RL_NewObjectA" result="Object *">
			<arg name="resfile" type="RESOURCEFILE"/>
			<arg name="resid" type="RESOURCEID"/>
			<arg name="tags" type="struct TagItem *"/>
		</method>
		<method name="RL_NewObject" result="Object *">
			<arg name="resfile" type="RESOURCEFILE"/>
			<arg name="resid" type="RESOURCEID"/>
			<vararg name="tag1" type="Tag"/>
		</method>
		<method name="RL_DisposeObject" result="VOID">
			<arg name="resfile" type="RESOURCEFILE"/>
			<arg name="obj" type="Object *"/>
		</method>
		<method name="RL_NewGroupA" result="Object **">
			<arg name="resfile" type="RESOURCEFILE"/>
			<arg name="id" type="RESOURCEID"/>
			<arg name="taglist" type="struct TagItem *"/>
		</method>
		<method name="RL_NewGroup" result="Object **">
			<arg name="resfile" type="RESOURCEFILE"/>
			<arg name="id" type="RESOURCEID"/>
			<vararg name="tag1" type="Tag"/>
		</method>
		<method name="RL_DisposeGroup" result="VOID">
			<arg name="resfile" type="RESOURCEFILE"/>
			<arg name="obj" type="Object **"/>
		</method>
		<method name="RL_GetObjectArray" result="Object **">
			<arg name="resfile" type="RESOURCEFILE"/>
			<arg name="obj" type="Object *"/>
			<arg name="id" type="RESOURCEID"/>
		</method>
		<method name="RL_SetResourceScreen" result="BOOL">
			<arg name="resfile" type="RESOURCEFILE"/>
			<arg name="screen" type="struct Screen *"/>
		</method>
	</interface>
</library>

=== sacredbanana/AmigaSDK-gcc/amigaos4/sdk/ppc-amigaos/SDK/include/interfaces/amigainput.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE library SYSTEM "library.dtd">
<!-- autogenerated by fdtrans v51.22 -->
<library name="amigainput" basename="AIN_Base" openname="amigainput.library">
	<include>amigainput/amigainput.h</include>
	<include>utility/tagitem.h</include>
	<interface name="main" version="1.0" struct="AIN_IFace" prefix="_AIN__" asmprefix="IAIN_" global="IAIN_">
		<method name="Obtain" result="uint32"/>
		<method name="Release" result="uint32"/>
		<method name="Expunge" result="void" status="unimplemented"/>
		<method name="Clone" result="struct Interface *" status="unimplemented"/>
		<method name="AIN_GetError" result="ULONG">
			<arg name="ctx" type="APTR"/>
		</method>
		<method name="AIN_GetErrorString" result="STRPTR">
			<arg name="error_code" type="ULONG"/>
		</method>
		<method name="AIN_CreateContext" result="APTR">
			<arg name="api_version" type="ULONG"/>
			<arg name="tags" type="struct TagItem *"/>
		</method>
		<method name="AIN_DeleteContext" result="VOID">
			<arg name="ctx" type="APTR"/>
		</method>
		<method name="AIN_EnumDevices" result="BOOL">
			<arg name="ctx" type="APTR"/>
			<arg name="enumfunc" type="APTR"/>
			<arg name="user_data" type="APTR"/>
		</method>
		<method name="AIN_Query" result="BOOL">
			<arg name="ctx" type="APTR"/>
			<arg name="device_id" type="AIN_DeviceID"/>
			<arg name="qParameter" type="ULONG"/>
			<arg name="qArg" type="ULONG"/>
			<arg name="result" type="APTR"/>
			<arg name="result_length" type="ULONG"/>
		</method>
		<method name="AIN_ObtainDevice" result="AIN_DeviceHandle *">
			<arg name="ctx" type="APTR"/>
			<arg name="device_id" type="AIN_DeviceID"/>
		</method>
		<method name="AIN_ReleaseDevice" result="VOID">
			<arg name="ctx" type="APTR"/>
			<arg name="handle" type="AIN_DeviceHandle *"/>
		</method>
		<method name="AIN_SetDeviceParameter" result="BOOL">
			<arg name="ctx" type="APTR"/>
			<arg name="handle" type="AIN_DeviceHandle *"/>
			<arg name="dParameter" type="ULONG"/>
			<arg name="dArg" type="ULONG"/>
		</method>
		<method name="AIN_GetEvent" result="AIN_InputEvent *">
			<arg name="ctx" type="APTR"/>
		</method>
		<method name="AIN_FreeEvent" result="VOID">
			<arg name="ctx" type="APTR"/>
			<arg name="event" type="AIN_InputEvent *"/>
		</method>
		<method name="AIN_ReadDevice" result="BOOL">
			<arg name="ctx" type="APTR"/>
			<arg name="handle" type="AIN_DeviceHandle *"/>
			<arg name="data" type="APTR *"/>
		</method>
		<method name="AIN_Set" result="BOOL">
			<arg name="ctx" type="APTR"/>
			<arg name="tags" type="struct TagItem *"/>
		</method>
		<method name="AIN_RequestDevice" result="struct _AIN_RequesterResult *">
			<arg name="ctx" type="APTR"/>
			<arg name="tags" type="struct TagItem *"/>
		</method>
		<method name="AIN_FreeRequest" result="VOID">
			<arg name="ctx" type="APTR"/>
			<arg name="result" type="struct _AIN_RequesterResult *"/>
		</method>
	</interface>
</library>

=== sacredbanana/AmigaSDK-gcc/ppc-amigaos/SDK/include/interfaces/potgo.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE library SYSTEM "library.dtd">
<!-- autogenerated by fdtrans v50.9 -->
<library name="potgo" basename="PotgoBase" openname="potgo.library">
	<include>exec/types.h</include>
	<interface name="main" version="1.0" struct="PotgoIFace" prefix="_Potgo_" asmprefix="IPotgo" global="IPotgo">
		<method name="Obtain" result="ULONG"/>
		<method name="Release" result="ULONG"/>
		<method name="Expunge" result="void" status="unimplemented"/>
		<method name="Clone" result="struct Interface *" status="unimplemented"/>
		<method name="AllocPotBits" result="UWORD">
			<arg name="bits" type="UWORD"/>
		</method>
		<method name="FreePotBits" result="VOID">
			<arg name="bits" type="UWORD"/>
		</method>
		<method name="WritePotgo" result="VOID">
			<arg name="word" type="UWORD"/>
			<arg name="mask" type="UWORD"/>
		</method>
	</interface>
</library>
